package com.hackhome.loans.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hackhome.loans.bean.ApplyRecordModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "APPLY_RECORD_MODEL".
*/
public class ApplyRecordModelDao extends AbstractDao<ApplyRecordModel, Long> {

    public static final String TABLENAME = "APPLY_RECORD_MODEL";

    /**
     * Properties of entity ApplyRecordModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property State = new Property(1, int.class, "state", false, "STATE");
        public final static Property TaskId = new Property(2, int.class, "taskId", false, "TASK_ID");
        public final static Property BtnPos = new Property(3, int.class, "btnPos", false, "BTN_POS");
    }


    public ApplyRecordModelDao(DaoConfig config) {
        super(config);
    }
    
    public ApplyRecordModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"APPLY_RECORD_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"STATE\" INTEGER NOT NULL ," + // 1: state
                "\"TASK_ID\" INTEGER NOT NULL ," + // 2: taskId
                "\"BTN_POS\" INTEGER NOT NULL );"); // 3: btnPos
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"APPLY_RECORD_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ApplyRecordModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getState());
        stmt.bindLong(3, entity.getTaskId());
        stmt.bindLong(4, entity.getBtnPos());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ApplyRecordModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getState());
        stmt.bindLong(3, entity.getTaskId());
        stmt.bindLong(4, entity.getBtnPos());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ApplyRecordModel readEntity(Cursor cursor, int offset) {
        ApplyRecordModel entity = new ApplyRecordModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // state
            cursor.getInt(offset + 2), // taskId
            cursor.getInt(offset + 3) // btnPos
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ApplyRecordModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setState(cursor.getInt(offset + 1));
        entity.setTaskId(cursor.getInt(offset + 2));
        entity.setBtnPos(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ApplyRecordModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ApplyRecordModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ApplyRecordModel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
